Add Default env variables on CES V2 Orchestration Dockerfile
sdhealthconnect/leap-demos pull request #20
Opened 2020-07-15 23:51 UTC by sgroh

2020-07-15 23:53 UTC, mojitoj commented
@sgroh preferably we should not hard-code these values here in the Dockerfile. Is it possible to read these env variables from the cloudbuild environment so that they are not hard-coded in the repo?

2020-07-15 23:54 UTC, mojitoj requested changes

2020-07-15 23:54 UTC, mojitoj commented on leap-ces-v2-orchestration/Dockerfile
> +ENV CDS_HOST_URL=https://sdhc-leap.appspot.com
as commented on the PR

2020-07-16 00:23 UTC, sgroh commented
> @sgroh preferably we should not hard-code these values here in the Dockerfile. Is it possible to read these env variables from the cloudbuild environment so that they are not hard-coded in the repo?

We always have the option to override them calling the docker with such environment variables when we run the container i.e: 
`docker run -e "CDS_HOST_URL=new_URL" `
BTW, if we want to remove this from the repository the solution should take the longest path, because when you select `Build Configuration: Dockerfile` on the trigger there is no option to add custom environment variables. In order to do that is necessary to specify `Cloud Build Configuration file (yaml or json)` option and add a couple of manual steps inside a new cloudbuild.yaml file. This last step is not the default way to resolve the CD but we can try this if having env variables inside a Dockerfile is not an option here. IMO have default values for mandatory env variables should be a must, but having them externalized is a good nice to have.

2020-07-16 01:01 UTC, mojitoj commented
I think it's just not good practice to have specific deployment configurations like this hard coded in the repo. What I had in mind was to do something like this:
```
environment
  CDS_HOST_URL =${_CDS_HOST_URL}
```
in which the right-hand side is an env variable injected by build trigger at build time and can be defined on the build trigger.

2020-07-16 19:05 UTC, ddecouteau approved these changes

2020-07-16 20:13 UTC, mojitoj approved these changes

2020-07-16 21:22 UTC, merged