Change CCDA Test URL from personal repository to Continuous Delivery …
sdhealthconnect/leap-demos pull request #40
Opened 2020-07-27 19:02 UTC by sgroh

Change CCDA Test URL from personal repository to Continuous Delivery one.

2020-07-27 19:03 UTC, mojitoj commented on leap-ces-ccda-orchestration/src/test/java/gov/hhs/onc/leap/ces/ccda/orchestration/service/CCDAOrchestrationServiceTest.java
> +        String result = doRequest(hookRequestWithData);
This should be moved to a config file.

2020-07-27 19:04 UTC, mojitoj requested changes

2020-07-27 19:04 UTC, mojitoj commented on leap-ces-ccda-orchestration/src/test/java/gov/hhs/onc/leap/ces/ccda/orchestration/service/CCDAOrchestrationServiceTest.java
> +    private String host =  "https://sdhc-leap-ccda-axz2tb4tma-uc.a.run.app";
This should be moved to a config file.

2020-07-27 19:49 UTC, sgroh commented on leap-ces-ccda-orchestration/src/test/java/gov/hhs/onc/leap/ces/ccda/orchestration/service/CCDAOrchestrationServiceTest.java
> +    private String host =  "https://sdhc-leap-ccda-axz2tb4tma-uc.a.run.app";
done.

2020-07-27 22:03 UTC, mojitoj approved these changes

2020-07-27 22:03 UTC, mojitoj commented on leap-ces-ccda-orchestration/src/test/resources/application-test.yaml
> +cds:
I don't see where these are used?

2020-07-28 00:15 UTC, sgroh commented on leap-ces-ccda-orchestration/src/test/resources/application-test.yaml
> +cds:
This is used when you annotate a test with @SpringBootApplication, this allows to load application context configuration and therefore allows us to use @Value on tests. Without this the test will fails creating the context for the respective service  `CCDAOrchestrationService`.

2020-07-28 01:40 UTC, merged